[package]
name = "surreal-project"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
surrealdb = "2.2.1"
tokio = { version = "1.44.1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0", features = ["derive"] }
